openapi: 3.0.0
info:
  title: Django Friends Service
  version: 1.0.0
paths:
  /api/users/:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input data

  /api/friend-request/:
    post:
      summary: Send a friend request to another user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to_user:
                  type: integer
      responses:
        '201':
          description: Friend request sent successfully
        '400':
          description: Invalid input data

  /api/friend-request/{friend_request_id}/:
    put:
      summary: Accept or reject a friend request
      parameters:
        - in: path
          name: friend_request_id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  enum: [accept, reject]
      responses:
        '200':
          description: Friend request accepted or rejected
        '400':
          description: Invalid input data

  /api/friend-requests/:
    get:
      summary: Get a list of incoming friend requests
      responses:
        '200':
          description: A list of incoming friend requests

  /api/friends/:
    get:
      summary: Get a list of friends
      responses:
        '200':
          description: A list of friends

  /api/friendship-status/{user_id}/:
    get:
      summary: Get the friendship status with another user
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Friendship status

  /api/friend-remove/{user_id}/:
    delete:
      summary: Remove a friend
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Friend removed successfully
        '404':
          description: No friendship found
