version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - /Users/igorkarpov/Documents/GitHub/karpovigor/Python/dyplom/my_project/my_app
      - /Users/igorkarpov/Documents/GitHub/karpovigor/Python/dyplom/my_project/db.sqlite3
